// Oscar's Classic Model Cars Collection Database
// Based on the original collection from oscarcarcollection.com

const carsCollection = [
    // ===== 1910 HUDSON MODELS =====
    {
        id: 1,
        name: "Hudson Model 20",
        year: 1910,
        country: "USA",
        type: "Touring",
        manufacturer: "Gowland & Gowland",
        modelNumber: "Kit",
        productionDate: "1956",
        scale: "1:36",
        madeIn: "USA",
        material: "Plastic",
        icon: "🚗",
        description: "An assembled kit model of the historic 1910 Hudson Model 20. Hudson Motor Car Company was founded in 1909 by Roy Chapin and financed by J.L. Hudson. This touring car features the classic open-top design of the era."
    },
    {
        id: 2,
        name: "Hudson Model 20",
        year: 1910,
        country: "USA",
        type: "Touring",
        manufacturer: "Lansdowne",
        modelNumber: "N71",
        productionDate: "2009",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "A finely detailed white metal replica of the 1910 Hudson Model 20 from Lansdowne's prestigious collection. Known for exceptional craftsmanship and historical accuracy."
    },
    {
        id: 3,
        name: "Hudson Model 20",
        year: 1910,
        country: "USA",
        type: "Touring",
        manufacturer: "Lansdowne",
        modelNumber: "N20a",
        productionDate: "2005",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        icon: "🚗",
        description: "A diecast version of the 1910 Hudson from Lansdowne's collection, showcasing the elegant lines of this early American automobile."
    },

    // ===== ROLLS ROYCE MODELS =====
    {
        id: 4,
        name: "Rolls Royce Silver Ghost",
        year: 1907,
        country: "England",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-10-1",
        productionDate: "1969",
        scale: "1:48",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚙",
        description: "The legendary Rolls Royce Silver Ghost, widely regarded as 'the best car in the world' during its era. This Matchbox Models of Yesteryear piece captures the elegance of early Rolls Royce craftsmanship."
    },
    {
        id: 5,
        name: "Rolls Royce Silver Ghost Touring",
        year: 1907,
        country: "England",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y7-1",
        productionDate: "1957-1960",
        scale: "1:55",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚙",
        description: "From the original Matchbox Models of Yesteryear first series, this Silver Ghost touring car represents the pinnacle of Edwardian luxury motoring."
    },

    // ===== MERCEDES MODELS =====
    {
        id: 6,
        name: "Mercedes Grand Prix",
        year: 1908,
        country: "Germany",
        type: "Racing",
        manufacturer: "Matchbox",
        modelNumber: "Y-10-1",
        productionDate: "1958-1959",
        scale: "1:54",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🏎️",
        description: "A racing legend - the 1908 Mercedes Grand Prix car. This model from the Matchbox Yesteryear first series captures the spirit of early motorsport when Mercedes dominated the racing circuits."
    },
    {
        id: 7,
        name: "Mercedes Benz",
        year: 1904,
        country: "Germany",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-9",
        productionDate: "1958",
        scale: "1:50",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚗",
        description: "An early Mercedes Benz from the dawn of the automobile age. This Matchbox Yesteryear model represents the pioneering spirit of German automotive engineering."
    },

    // ===== BENTLEY MODELS =====
    {
        id: 8,
        name: "Bentley Le Mans",
        year: 1929,
        country: "England",
        type: "Racing",
        manufacturer: "Matchbox",
        modelNumber: "Y5-1",
        productionDate: "1958-1961",
        scale: "1:55",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🏎️",
        description: "The legendary Bentley Le Mans racer, celebrating the 'Bentley Boys' era when British racing green dominated the famous 24-hour endurance race. A true icon of motorsport history."
    },
    {
        id: 9,
        name: "Bentley 4.5 Litre Supercharged",
        year: 1930,
        country: "England",
        type: "Racing",
        manufacturer: "Matchbox",
        modelNumber: "Y-2",
        productionDate: "1984",
        scale: "1:48",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🏎️",
        description: "The famous 'Blower Bentley' - Sir Henry Birkin's supercharged racing machine that became one of the most iconic British racing cars of all time."
    },

    // ===== SENTINEL STEAM WAGON =====
    {
        id: 10,
        name: "Sentinel Steam Wagon",
        year: 1928,
        country: "England",
        type: "Truck",
        manufacturer: "Matchbox",
        modelNumber: "Y4-1",
        productionDate: "1956",
        scale: "1:100",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚚",
        description: "A working steam wagon from the Sentinel company of Shrewsbury. These steam-powered trucks were a common sight on British roads before the dominance of diesel."
    },

    // ===== LOCOMOTIVES =====
    {
        id: 11,
        name: "Santa Fe Locomotive",
        year: 1862,
        country: "USA",
        type: "Locomotive",
        manufacturer: "Matchbox",
        modelNumber: "Y-13",
        productionDate: "1959",
        scale: "1:112",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚂",
        description: "A classic American 4-4-0 locomotive from the Santa Fe Railroad, representing the golden age of American railroading during the expansion westward."
    },
    {
        id: 12,
        name: "Duke of Connaught Locomotive",
        year: 1903,
        country: "England",
        type: "Locomotive",
        manufacturer: "Matchbox",
        modelNumber: "Y-14",
        productionDate: "1959",
        scale: "1:130",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚂",
        description: "A Great Western Railway locomotive named after the Duke of Connaught. This elegant engine represents the pride of British railway engineering."
    },

    // ===== LONDON TRAMCAR =====
    {
        id: 13,
        name: "London E Class Tramcar",
        year: 1907,
        country: "England",
        type: "Tramcar",
        manufacturer: "Matchbox",
        modelNumber: "Y-3",
        productionDate: "1956-1965",
        scale: "1:130",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚃",
        description: "A London E Class electric tramcar that served the streets of London in the early 20th century. These iconic vehicles were a vital part of London's public transport network."
    },

    // ===== LEYLAND MODELS =====
    {
        id: 14,
        name: "Leyland Bus",
        year: 1920,
        country: "England",
        type: "Bus",
        manufacturer: "Matchbox",
        modelNumber: "Y-7",
        productionDate: "1957-1960",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚌",
        description: "A classic Leyland bus from the 1920s, when motorized buses began replacing horse-drawn omnibuses on Britain's streets."
    },

    // ===== ADDITIONAL LANSDOWNE MODELS =====
    {
        id: 15,
        name: "Austin A40 Devon",
        year: 1949,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 3",
        productionDate: "1993-1999",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The post-war Austin A40 Devon, a popular British family car that helped motorize Britain in the austerity years following World War II."
    },
    {
        id: 16,
        name: "Ford Model A Roadster",
        year: 1930,
        country: "USA",
        type: "Roadster",
        manufacturer: "Lansdowne",
        modelNumber: "No. 4",
        productionDate: "1993-1997",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "Henry Ford's successor to the legendary Model T. The Model A Roadster combined affordability with style, making it a popular choice in Depression-era America."
    },
    {
        id: 17,
        name: "MG Magnette ZA",
        year: 1954,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 7a",
        productionDate: "2010-2013",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The elegant MG Magnette ZA, combining MG's sporting heritage with practical four-door saloon practicality. A sophisticated choice for the discerning 1950s motorist."
    },
    {
        id: 18,
        name: "Triumph Mayflower",
        year: 1952,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 10",
        productionDate: "1995-2001",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The distinctive Triumph Mayflower with its razor-edge styling. Though unconventional, this small luxury car found a loyal following in both Britain and America."
    },
    {
        id: 19,
        name: "Morris Oxford MO",
        year: 1950,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 27",
        productionDate: "2000-2005",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        icon: "🚗",
        description: "The Morris Oxford MO, a dependable British family saloon that epitomized the solid, no-nonsense approach to post-war motoring."
    },
    {
        id: 20,
        name: "Jowett Javelin",
        year: 1948,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 67",
        productionDate: "2013",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The innovative Jowett Javelin, with its advanced flat-four engine and aerodynamic design. A car ahead of its time from the small Yorkshire manufacturer."
    },
    {
        id: 21,
        name: "Austin A90 Atlantic",
        year: 1950,
        country: "England",
        type: "Touring",
        manufacturer: "Lansdowne",
        modelNumber: "No. 72",
        productionDate: "2009",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The Austin A90 Atlantic, designed specifically for the American market. Its flamboyant styling and powerful engine made it a distinctive export success."
    },

    // ===== ADDITIONAL MATCHBOX MODELS =====
    {
        id: 22,
        name: "Allchin Traction Engine",
        year: 1925,
        country: "England",
        type: "Traction Engine",
        manufacturer: "Matchbox",
        modelNumber: "Y-1",
        productionDate: "1956-1959",
        scale: "1:80",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚜",
        description: "An Allchin agricultural traction engine, representing the steam power that transformed farming before the internal combustion engine took over."
    },
    {
        id: 23,
        name: "London Horse-Drawn Bus",
        year: 1886,
        country: "England",
        type: "Horse-Drawn Bus",
        manufacturer: "Matchbox",
        modelNumber: "Y-12",
        productionDate: "1959",
        scale: "1:89",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🐴",
        description: "A Victorian London horse-drawn omnibus, the predecessor to motorized public transport. These colorful vehicles were a ubiquitous sight in 19th century London."
    },
    {
        id: 24,
        name: "Spyker Tourer",
        year: 1904,
        country: "Netherlands",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-16",
        productionDate: "1961",
        scale: "1:52",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🚗",
        description: "A rare Dutch Spyker touring car, from the pioneering Dutch automobile manufacturer known for innovative engineering including the first four-wheel drive race car."
    },
    {
        id: 25,
        name: "Opel Coupe",
        year: 1909,
        country: "Germany",
        type: "Coupe",
        manufacturer: "Matchbox",
        modelNumber: "Y-4",
        productionDate: "1966",
        scale: "1:48",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "An elegant Opel Coupe from the early days of German automobile manufacturing. Opel was already becoming one of Europe's largest car producers."
    },

    // ===== FORD MODELS =====
    {
        id: 26,
        name: "Ford Model T",
        year: 1912,
        country: "USA",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-1",
        productionDate: "1964",
        scale: "1:40",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "The car that put America on wheels - Henry Ford's revolutionary Model T. Its affordable price and reliable performance made automobile ownership possible for millions."
    },
    {
        id: 27,
        name: "Ford Model T Van",
        year: 1912,
        country: "USA",
        type: "Van",
        manufacturer: "Matchbox",
        modelNumber: "Y-12",
        productionDate: "1978",
        scale: "1:35",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚐",
        description: "A commercial variant of the Model T, showing how Ford's universal design was adapted for business use across America."
    },

    // ===== BUGATTI MODELS =====
    {
        id: 28,
        name: "Bugatti Type 35",
        year: 1926,
        country: "France",
        type: "Racing",
        manufacturer: "Matchbox",
        modelNumber: "Y-6",
        productionDate: "1961",
        scale: "1:50",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear First Series",
        icon: "🏎️",
        description: "The legendary Bugatti Type 35, arguably the most successful racing car in history. Its beautiful design and racing success made Bugatti a legend in motorsport."
    },
    {
        id: 29,
        name: "Bugatti Type 35",
        year: 1928,
        country: "France",
        type: "Racing",
        manufacturer: "Matchbox",
        modelNumber: "Y-6",
        productionDate: "1979",
        scale: "1:45",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🏎️",
        description: "A later issue of the iconic Bugatti Type 35, the racing car that won over 1,000 races including five consecutive Targa Florio victories."
    },

    // ===== STUTZ MODELS =====
    {
        id: 30,
        name: "Stutz Bearcat",
        year: 1914,
        country: "USA",
        type: "Sports",
        manufacturer: "Matchbox",
        modelNumber: "Y-11",
        productionDate: "1969",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🏎️",
        description: "The Stutz Bearcat, America's answer to European sports cars. This stripped-down speedster became an icon of American sporting motoring in the teens and twenties."
    },

    // ===== CADILLAC MODELS =====
    {
        id: 31,
        name: "Cadillac Model 30",
        year: 1910,
        country: "USA",
        type: "Touring",
        manufacturer: "Franklin Mint",
        modelNumber: "FM-30",
        productionDate: "1990",
        scale: "1:43",
        madeIn: "China",
        material: "Diecast",
        icon: "🚗",
        description: "A luxury Cadillac Model 30 from the dawn of American luxury motoring. Cadillac was already establishing itself as 'The Standard of the World.'"
    },

    // ===== PACKARD MODELS =====
    {
        id: 32,
        name: "Packard Victoria",
        year: 1930,
        country: "USA",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-15",
        productionDate: "1969",
        scale: "1:46",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "An elegant Packard Victoria, representing the height of American luxury automobile manufacturing before the Great Depression changed everything."
    },

    // ===== RENAULT MODELS =====
    {
        id: 33,
        name: "Renault 12/16",
        year: 1910,
        country: "France",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-5",
        productionDate: "1979",
        scale: "1:45",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "A French Renault from the pioneer era of motoring, when Renault was establishing itself as one of Europe's leading automobile manufacturers."
    },

    // ===== DAIMLER MODELS =====
    {
        id: 34,
        name: "Daimler 1911",
        year: 1911,
        country: "England",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-13",
        productionDate: "1965",
        scale: "1:45",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "A stately Daimler, the preferred motor car of British royalty. King Edward VII's patronage established Daimler as the premier British luxury marque."
    },

    // ===== THOMAS FLYABOUT =====
    {
        id: 35,
        name: "Thomas Flyabout",
        year: 1909,
        country: "USA",
        type: "Sports",
        manufacturer: "Matchbox",
        modelNumber: "Y-12",
        productionDate: "1967",
        scale: "1:42",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "The Thomas Flyer, famous for winning the 1908 New York to Paris race - the greatest automotive adventure of the pioneer era."
    },

    // ===== FIRE ENGINES =====
    {
        id: 36,
        name: "Merryweather Fire Engine",
        year: 1904,
        country: "England",
        type: "Fire Engine",
        manufacturer: "Matchbox",
        modelNumber: "Y-9",
        productionDate: "1968",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚒",
        description: "A Merryweather steam-powered fire engine, representing the transition from horse-drawn to motorized firefighting equipment in early 20th century Britain."
    },

    // ===== ADDITIONAL VINTAGE MODELS =====
    {
        id: 37,
        name: "Vauxhall Prince Henry",
        year: 1914,
        country: "England",
        type: "Sports",
        manufacturer: "Matchbox",
        modelNumber: "Y-2",
        productionDate: "1970",
        scale: "1:45",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🏎️",
        description: "The Vauxhall Prince Henry, Britain's first true sports car. Named after Prince Henry of Prussia's touring car trials, it set the template for sporting motoring."
    },
    {
        id: 38,
        name: "Lagonda Drophead Coupe",
        year: 1938,
        country: "England",
        type: "Coupe",
        manufacturer: "Matchbox",
        modelNumber: "Y-11",
        productionDate: "1973",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "An elegant Lagonda Drophead Coupe, representing the finest in pre-war British grand touring. Lagonda's craftsmanship rivaled Bentley and Rolls-Royce."
    },
    {
        id: 39,
        name: "Hispano-Suiza",
        year: 1938,
        country: "France",
        type: "Touring",
        manufacturer: "Matchbox",
        modelNumber: "Y-17",
        productionDate: "1973",
        scale: "1:48",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🚗",
        description: "The legendary Hispano-Suiza, perhaps the most exclusive and expensive car of the pre-war era. Favored by royalty and film stars alike."
    },
    {
        id: 40,
        name: "Auburn Speedster 851",
        year: 1935,
        country: "USA",
        type: "Sports",
        manufacturer: "Matchbox",
        modelNumber: "Y-19",
        productionDate: "1980",
        scale: "1:45",
        madeIn: "England",
        material: "Diecast",
        series: "Models of Yesteryear",
        icon: "🏎️",
        description: "The stunning Auburn 851 Speedster, designed by Gordon Buehrig. Each car came with a plaque certifying it had been tested at over 100 mph."
    },

    // ===== CORGI MODELS =====
    {
        id: 41,
        name: "Aston Martin DB5",
        year: 1965,
        country: "England",
        type: "Sports",
        manufacturer: "Corgi",
        modelNumber: "270",
        productionDate: "1965",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        icon: "🚗",
        description: "The famous James Bond Aston Martin DB5, one of the most collectible toy cars ever made. Features include ejector seat and rotating license plates."
    },

    // ===== DINKY MODELS =====
    {
        id: 42,
        name: "Rolls Royce Phantom V",
        year: 1962,
        country: "England",
        type: "Limousine",
        manufacturer: "Dinky",
        modelNumber: "152",
        productionDate: "1962",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        icon: "🚙",
        description: "A majestic Rolls Royce Phantom V limousine, the choice of heads of state and royalty worldwide. This Dinky model captures its imposing presence."
    },
    {
        id: 43,
        name: "Jaguar E-Type",
        year: 1961,
        country: "England",
        type: "Sports",
        manufacturer: "Dinky",
        modelNumber: "120",
        productionDate: "1962",
        scale: "1:43",
        madeIn: "England",
        material: "Diecast",
        icon: "🏎️",
        description: "The Jaguar E-Type, described by Enzo Ferrari as 'the most beautiful car ever made.' This Dinky model captures the flowing lines of the original."
    },

    // ===== MORE LANSDOWNE BRITISH CLASSICS =====
    {
        id: 44,
        name: "Vauxhall Cresta PA",
        year: 1959,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 5",
        productionDate: "1994-1998",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The Vauxhall Cresta PA with its American-influenced styling and distinctive chrome work. A popular choice for British families in the late 1950s."
    },
    {
        id: 45,
        name: "Humber Super Snipe",
        year: 1958,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 8",
        productionDate: "1995-2000",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The stately Humber Super Snipe, favored by government officials and company directors. A proper British executive car."
    },
    {
        id: 46,
        name: "Singer Gazelle",
        year: 1958,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 12",
        productionDate: "1996-2002",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The Singer Gazelle, an upmarket version of the Hillman Minx with leather interior and walnut dashboard. A small car with big-car pretensions."
    },
    {
        id: 47,
        name: "Sunbeam Rapier",
        year: 1957,
        country: "England",
        type: "Coupe",
        manufacturer: "Lansdowne",
        modelNumber: "No. 15",
        productionDate: "1997-2003",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The sporty Sunbeam Rapier hardtop coupe, with its distinctive two-tone paintwork and rally pedigree. A stylish alternative to the family saloon."
    },
    {
        id: 48,
        name: "Standard Vanguard",
        year: 1953,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 18",
        productionDate: "1998-2004",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The Standard Vanguard Phase II, designed to be a 'world car' for export markets. Its distinctive styling was inspired by American designs."
    },
    {
        id: 49,
        name: "Wolseley 6/90",
        year: 1954,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 22",
        productionDate: "1999-2005",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The Wolseley 6/90 with its distinctive illuminated grille badge. A favorite of police forces and those who appreciated traditional British luxury."
    },
    {
        id: 50,
        name: "Armstrong Siddeley Sapphire",
        year: 1953,
        country: "England",
        type: "Saloon",
        manufacturer: "Lansdowne",
        modelNumber: "No. 25",
        productionDate: "2000-2006",
        scale: "1:43",
        madeIn: "England",
        material: "White Metal",
        icon: "🚗",
        description: "The prestigious Armstrong Siddeley Sapphire, favored by the establishment. Its Sphinx mascot and quality engineering made it a natural choice for those who wanted something different from the usual Rolls-Royce."
    }
];

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = carsCollection;
}
